#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx test',
    source=['mts_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target='mts_tests',
    use=['mts', 'gtest'],
    test_files=['pes_dump', 'test.ts'])
